### PR TITLE
Fix: various issues with tab audio behaviour

### PR DESCRIPTION
**Pull request by PikaDude**
- Changing an option while tab was playing audio did not do anything
- Music randomly starting when opening new tabs

### CODE REVIEW

**Comment by jordigarcl** [comment]
Found another instance of the bug so I've tried to find it and reproduce it in this same PR. I'll probably include some refactoring along the way.

**Comment by jordigarcl** [comment]
Added some comments and printDebug statements. Also did a change you may want to look at in my last commit. See commit message for context.

**Review by jordigarcl — APPROVED** [review]
Seems to work good and LGTM

**Comment by PikaDude** [comment]
Next time, try to keep irrelevant commits in seperate pull requests. I'll check the changes when I get the chance.

**Comment by jordigarcl** [comment]
Removed my commits. Sorry, will include them in a separate PR.

**Pull request merged**
