### PR TITLE
Fix: town tune playing sets off the paused event

### PR DESCRIPTION
**Pull request by PikaDude**
This PR fixes the bug that causes the paused event to trigger when the town tune plays. This bug causes the extension to update it's options setting `paused` to be true, so when the extension boots the next time, the music will be paused. The bug also updates the badge to be in a paused state.

### CODE REVIEW

**Comment by jordigarcl** [comment]
I don't quite understand the bug this fixes, so I can not give significant feedback here.

Both `develop` and `fix/town-tune-pauses` work as expected on my machine: fading out hourly music, playing town tune and starting the new hour. Am I missing something?

**Comment by PikaDude** [comment]
Yes. As stated, the bug is that once the town tune plays on the hour, the option `paused` is mistakenly set to `true`, so if the extension restarts, it will be in a paused state rather than a playing state.

**Comment by jordigarcl** [comment]
Oh I see. My fault, interpreted 'restarted' as 'when the next hour music starts playing'. The changes make sense then.

**Review by jordigarcl — APPROVED** [review]
Yup, just tried it 👍

**Pull request merged**
